name: osm_nominatim_geocoding
description: A simple wrapper for OSM Nominatim Geocoding API
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  latlong2: ^0.9.1
  geojson_vi: ^2.2.5
  dio: ^5.7.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
